version: '3.8'

services:
    # MySQL Database Service
    mysql:
        image: mysql:8.3
        container_name: mysql
        environment:
            MYSQL_DATABASE: resume_builder
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - '12345:3306'
        networks:
            - resume_builder_service

    # MongoDB Service
    mongo:
        image: mongo:8.0.3
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodbusre
            MONGO_INITDB_ROOT_PASSWORD: mongodbpass
        volumes:
            - mongo_data:/data/db
        ports:
            - '12346:27017'
        networks:
            - resume_builder_service

    # Redis Service with Password and Data Volume
    redis:
        image: redis:7-alpine
        container_name: redis
        environment:
            - REDIS_PASSWORD=redis
        command: ['redis-server', '--requirepass', 'redis']
        volumes:
            - redis_data:/data
        ports:
            - '12347:6379'
        networks:
            - resume_builder_service

    # Redis Stack with RedisInsight GUI
    redis-stack:
        image: redis/redis-stack:latest
        container_name: redis-stack
        ports:
            - '12348:8001'
        networks:
            - resume_builder_service

volumes:
    mysql_data:
    mongo_data:
    redis_data:

networks:
    resume_builder_service:
